# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the TypeScript code
RUN npm run build

# Copy non-transpiled JS file(s) required in dist
# Assuming pinterest-scraper.js should be in dist along with the compiled files
RUN mkdir -p dist && cp pinterest-scraper.js dist/

# Command to run the MCP server via stdio
CMD [ "node", "dist/pinterest-mcp-server.js" ]
